name: Update README

on:
  schedule:
    - cron: "0 * * * *" # Updates every hour
  push:
    branches:
      - main

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Update README Stats
        uses: anuraghazra/github-readme-stats@master

      - name: Commit & Push
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add README.md
          git commit -m "Auto-update README stats"
          git push
